### ISSUE TITLE
config is undefined

### ISSUE THREAD

**Issue by spearmootz** [winstonjs/winston-compat#3]
node_modules\winston-compat\index.js:160
      ? config.colorize(options.level)
        ^

ReferenceError: config is not defined

**Comment by mattberther** [comment]
Also:

```
ReferenceError: util is not defined
at Object.exports.log (/container/node_modules/winston-compat/index.js:183:32)
at DailyRotateFile.log (/container/node_modules/winston-daily-rotate-file/daily-rotate-file.js:109:29)
```

when using `prettyPrint: true`.

**Comment by EvanDarwin** [comment]
```
ReferenceError: config is not defined at Object.exports.log (/sleepez/api/node_modules/winston-compat/index.js:162:9) at DailyRotateFile.log
```

Also experiencing this
